### ISSUE TITLE
[IP] Missing license on some 3rd party dependencies

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-context#80]
We could not identify the open-source license attached to the following dependencies. If you own the code, could you update it with a business-friendly license:
* de.atb.context/context-core
* de.atb.context/context-monitoring

**Comment by schlotze** [comment]
Both libraries are part of the Context Handling. The sour-code is located in this repository and they are under license EPL 2.0

**Comment by phkrief** [comment]
Oops! It seems that the tool I'm using is not able to recognize modules in a pom.xml file.
I will open a bug on that. Thx a lot
