### ISSUE TITLE
[IP] Dependencies using a GPL and AGPL license

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-context#81]
We identify some 3rd-party dependencies using a GPL or AGPL license. It could be an issue for the project:
* jpathwatch (https://mvnrepository.com/artifact/net.sf.jpathwatch/jpathwatch/0.95)
* pellet-jena (https://mvnrepository.com/artifact/com.github.ansell.pellet/pellet-jena)

Can you find an alternative to these libraries? If not, we could contact the owners to see if they would agree to create a new version based on a business-friendly license.
Thx

**Comment by philipreimer** [comment]
@phkrief PR #76 (in progress) will remove / replace these libraries

**Comment by phkrief** [comment]
Fixed ! thx
