### ISSUE TITLE
[IP] DASH Tool analysis

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-context#82]
Here are potential issues that a full IP review might identify when this code will be pushed in Eclipse:

License information could not be automatically verified for the following content:

maven/mavencentral/asm/asm-commons/3.3.1
maven/mavencentral/asm/asm-tree/3.3.1
maven/mavencentral/com.github.ansell.aterms/aterm-java/1.8.2-p1
maven/mavencentral/com.github.ansell.aterms/shared-objects/1.4.9-p1
maven/mavencentral/com.github.ansell.jjtraveler/jjtraveler/0.6
maven/mavencentral/com.github.ansell.pellet/pellet-common/2.3.6-ansell
maven/mavencentral/com.github.ansell.pellet/pellet-core/2.3.6-ansell
maven/mavencentral/com.github.ansell.pellet/pellet-datatypes/2.3.6-ansell
maven/mavencentral/com.github.ansell.pellet/pellet-el/2.3.6-ansell
maven/mavencentral/com.github.ansell.pellet/pellet-jena/2.3.6-ansell
maven/mavencentral/com.github.ansell.pellet/pellet-rules/2.3.6-ansell
maven/mavencentral/com.googlecode.mdock/mdock/1.1
maven/mavencentral/com.hermit-reasoner/org.semanticweb.hermit/1.3.8.3
maven/mavencentral/com.hp.hpl.jena/arq/2.8.7
maven/mavencentral/com.hp.hpl.jena/iri/0.8
maven/mavencentral/com.hp.hpl.jena/jena/2.6.4
maven/mavencentral/com.hp.hpl.jena/sdb/1.3.4
maven/mavencentral/com.hp.hpl.jena/tdb/0.8.10
maven/mavencentral/com.ibm.icu/icu4j/3.4.4
maven/mavencentral/com.jgoodies/jgoodies-common/1.8.1
maven/mavencentral/com.jgoodies/jgoodies-forms/1.9.0
maven/mavencentral/com.jgoodies/looks/2.2.2
maven/mavencentral/com.rabbitmq/amqp-client/5.14.0
maven/mavencentral/de.atb.context/context-core/2.0.0
maven/mavencentral/de.atb.context/context-monitoring/2.0.0
maven/mavencentral/edu.stanford.protege/org.protege.common/4.3.0
maven/mavencentral/edu.stanford.protege/org.protege.editor.core.application/4.3.0
maven/mavencentral/edu.stanford.protege/org.protege.editor.owl.codegeneration/1.0.2
maven/mavencentral/edu.stanford.protege/org.protege.editor.owl/4.3.0
maven/mavencentral/edu.stanford.protege/org.protege.xmlcatalog/1.0.3
maven/mavencentral/edu.stanford.protege/protege-owlapi-extensions/3.2.4
maven/mavencentral/javax/javaee-web-api/8.0.1
maven/mavencentral/msv/relaxngDatatype/20030225
maven/mavencentral/msv/xsdlib/20030225
maven/mavencentral/net.sf.jpathwatch/jpathwatch/0.95
maven/mavencentral/net.sourceforge.cobertura/cobertura/2.0
maven/mavencentral/net.sourceforge.owlapi/jfact/1.0.0
maven/mavencentral/net.sourceforge.owlapi/owlapi-api/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-apibinding/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-compatibility/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-distribution/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-impl/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-parsers/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-rio/5.1.19
maven/mavencentral/net.sourceforge.owlapi/owlapi-tools/5.1.19
maven/mavencentral/org.apache.ant/ant-launcher/1.7.0
maven/mavencentral/org.apache.cxf/cxf-rt-transports-http-jetty/3.4.5
maven/mavencentral/org.apache.cxf/cxf-rt-ws-policy/3.4.5
maven/mavencentral/org.apache.httpcomponents/httpclient-osgi/4.5.10
maven/mavencentral/org.apache.lucene/lucene-analyzers-common/8.11.0
maven/mavencentral/org.apache.lucene/lucene-core/8.11.0
maven/mavencentral/org.jgrapht/jgrapht-jdk1.5/0.7.3
maven/mavencentral/org.swinglabs/swing-worker/1.1
maven/mavencentral/org.swinglabs/swingx/1.6.1
maven/mavencentral/org.tukaani/xz/1.6
maven/mavencentral/xerces/xercesImpl/2.7.1

This content is either not correctly mapped by the system, or requires review.

**Comment by philipreimer** [comment]
@phkrief the dependencies listed below use Apache-2.0 license but are marked as `restricted` in dash report. Whereas other dependencies, which also use Apache-2.0 license (e.g. the other `cxf` dependencies), are marked as `approved`.

What exactly is the problem with these Apache-2.0 licensed dependencies?

```
maven/mavencentral/com.rabbitmq/amqp-client/5.14.0
maven/mavencentral/org.apache.cxf/cxf-rt-transports-http-jetty/3.4.5
maven/mavencentral/org.apache.cxf/cxf-rt-ws-policy/3.4.5
maven/mavencentral/org.apache.httpcomponents/httpclient-osgi/4.5.10
maven/mavencentral/org.apache.lucene/lucene-analyzers-common/8.11.0
maven/mavencentral/org.apache.lucene/lucene-core/8.11.0
```

**Comment by phkrief** [comment]
In several cases, the "restricted" is not a big issue. For example, I checked the library "cxf-rt-transports-http-jetty" version 3.4.5.
The DASH Tool requests 2 servers: Eclipse ORBIT and, if it cannot find it there, it requests ClearlyDefined.
So, usually, what I do is that I go directly on ClearlyDefine to retrieve the library:
https://clearlydefined.io/?sort=releaseDate&sortDesc=true&name=cxf-rt-transports-http-jetty
As you can see, it could find the library but not the version 3.4.5.
If you check the closest version, 3.4.4, it could discover the license but it is not properly declared using the tag SPDX. It is for this reason that the score of this version is so low
![image](https://user-images.githubusercontent.com/6196602/148390373-cb39073a-2073-4576-9813-0449901bd160.png).
Now, if you select another version, with a better score such as 3.3.11, the score is much better (80) and the score for the license is 60 which is the number that the DASH tool is checking for confidence. The number must be >= 60.
![image](https://user-images.githubusercontent.com/6196602/148390884-0f2150ac-0394-4d32-80bd-86996db9785e.png).

So you can either keep it like that and when we will push it in Eclipse, we will be required to create a CQ (: Contribution Questionnaire) and the IP team will check and will either accept this new version and add it to ORBIT or will ask you to select another one. or you select another one.

Actually, with an open-source license such Apache (or Eclipse or you name it), the owner can change anytime between 2 versions for another license. For example, you could put your code in GitHub using the EPL license initially then on a next version switch to GPL to finally on a third version switch to a proprietary license. You own the code, you do what ever you want.
When you push the code in a Foundation such as Eclipse, you cannot do that, unless you do a fork, but in this case, you will have to rename all your project.

HTH

**Comment by phkrief** [comment]
Btw, FYI, I try to see how I can shorten this list to identify only the main/real potential issues such as a GPL license or an unknown license
