### ISSUE TITLE
[IP] maven/mavencentral/net.sourceforge.cobertura/cobertura/2.0 is under GPL

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-context#93]
We have an issue with one of your dependencies:
maven/mavencentral/net.sourceforge.cobertura/cobertura/2.0
It is under the GPL 2.0 license and  will not be accepted by the Eclipse IP Review

Can you find a way to get rid of it?

Thx

PS: we find the same problem on the following repos:
smartclide-context
smartclide-context-core
smartclide-context-extraction
smartclide-context-monitoring
smartclide-smartclide-monitoring

**Comment by philipreimer** [comment]
@phkrief this dependency is removed in #83
